FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_API_URL=https://api.x-raydent.ru
ENV VITE_API_URL=$VITE_API_URL

COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY tsconfig.json ./
COPY tsconfig.app.json ./
COPY vite.config.ts ./
COPY index.html ./
COPY public ./public
COPY src ./src
RUN npx vite build

FROM nginx:1.27-alpine

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
