FROM node:22-alpine AS build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY index.html ./
COPY postcss.config.mjs ./
COPY vite.config.ts ./
COPY ATTRIBUTIONS.md ./
COPY README.md ./
COPY public ./public
COPY src ./src
COPY guidelines ./guidelines
RUN npx vite build

FROM nginx:1.27-alpine

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
